version: '3'
services:
  server:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
      - ~/Library/Caches/go-build:/root/.cache/go-build
      - ~/go:/root/go
    command: "go run ."
