load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "dungeonsandtrolls_proto",
    srcs = ["dungeonsandtrolls.proto"],
    deps = [
        "@go_googleapis//google/api:annotations_proto",
    ],
    visibility = ["//visibility:public"],
    strip_import_prefix = ""
)