type: google.api.Service
config_version: 3

http:
  rules:
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Game
      get: "/v1/game"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.GameLevel
      get: "/v1/game/{level}"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Players
      get: "/v1/players"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Levels
      get: "/v1/levels"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Register
      post: /v1/register
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Buy
      post: /v1/buy
      body: "identifiers"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.PickUp
      post: /v1/pick-up
      body: "identifier"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Move
      post: /v1/move
      body: "position"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Respawn
      post: /v1/respawn
      body: "respawn"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Skill
      post: /v1/skill
      body: "skill_use"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Commands
      post: /v1/commands
      body: "commands_batch"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.MonstersCommands
      post: /v1/monsters-commands
      body: "commands_for_monsters"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Yell
      post: /v1/yell
      body: "message"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.AssignSkillPoints
      post: /v1/assign-skill-points
      body: "attributes"