type: google.api.Service
config_version: 3

http:
  rules:
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Game
      get: "/v1/game"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Register
      post: /v1/register
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Buy
      post: /v1/buy
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Equip
      post: /v1/equip
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Drink
      post: /v1/drink
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Move
      post: /v1/move
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Attack
      post: /v1/attack
      body: "*"