type: google.api.Service
config_version: 3

http:
  rules:
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Game
      get: "/v1/game"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Register
      post: /v1/register
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Buy
      post: /v1/buy
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.PickUp
      post: /v1/pick-up
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Move
      post: /v1/move
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Respawn
      post: /v1/respawn
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Skill
      post: /v1/skill
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Commands
      post: /v1/commands
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.MonstersCommands
      post: /v1/monsters-commands
      body: "*"
    - selector: dungeonsandtrolls.DungeonsAndTrolls.Yell
      post: /v1/yell
      body: "*"