// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: proto/dungeonsandtrolls.proto

package dungeonsandtrolls

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DungeonsAndTrollsClient is the client API for DungeonsAndTrolls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DungeonsAndTrollsClient interface {
	Game(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GameState, error)
}

type dungeonsAndTrollsClient struct {
	cc grpc.ClientConnInterface
}

func NewDungeonsAndTrollsClient(cc grpc.ClientConnInterface) DungeonsAndTrollsClient {
	return &dungeonsAndTrollsClient{cc}
}

func (c *dungeonsAndTrollsClient) Game(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GameState, error) {
	out := new(GameState)
	err := c.cc.Invoke(ctx, "/dungeonsandtrolls.DungeonsAndTrolls/Game", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DungeonsAndTrollsServer is the server API for DungeonsAndTrolls service.
// All implementations must embed UnimplementedDungeonsAndTrollsServer
// for forward compatibility
type DungeonsAndTrollsServer interface {
	Game(context.Context, *emptypb.Empty) (*GameState, error)
	mustEmbedUnimplementedDungeonsAndTrollsServer()
}

// UnimplementedDungeonsAndTrollsServer must be embedded to have forward compatible implementations.
type UnimplementedDungeonsAndTrollsServer struct {
}

func (UnimplementedDungeonsAndTrollsServer) Game(context.Context, *emptypb.Empty) (*GameState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Game not implemented")
}
func (UnimplementedDungeonsAndTrollsServer) mustEmbedUnimplementedDungeonsAndTrollsServer() {}

// UnsafeDungeonsAndTrollsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DungeonsAndTrollsServer will
// result in compilation errors.
type UnsafeDungeonsAndTrollsServer interface {
	mustEmbedUnimplementedDungeonsAndTrollsServer()
}

func RegisterDungeonsAndTrollsServer(s grpc.ServiceRegistrar, srv DungeonsAndTrollsServer) {
	s.RegisterService(&DungeonsAndTrolls_ServiceDesc, srv)
}

func _DungeonsAndTrolls_Game_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DungeonsAndTrollsServer).Game(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dungeonsandtrolls.DungeonsAndTrolls/Game",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DungeonsAndTrollsServer).Game(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DungeonsAndTrolls_ServiceDesc is the grpc.ServiceDesc for DungeonsAndTrolls service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DungeonsAndTrolls_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dungeonsandtrolls.DungeonsAndTrolls",
	HandlerType: (*DungeonsAndTrollsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Game",
			Handler:    _DungeonsAndTrolls_Game_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dungeonsandtrolls.proto",
}
