// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: proto/dungeonsandtrolls.proto

package dungeonsandtrolls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weapon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Damage float32 `protobuf:"fixed32,2,opt,name=damage,proto3" json:"damage,omitempty"`
	Weight float32 `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dungeonsandtrolls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeonsandtrolls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_proto_dungeonsandtrolls_proto_rawDescGZIP(), []int{0}
}

func (x *Weapon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Weapon) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Weapon) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Items struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Weapons []*Weapon `protobuf:"bytes,1,rep,name=weapons,proto3" json:"weapons,omitempty"`
}

func (x *Items) Reset() {
	*x = Items{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dungeonsandtrolls_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeonsandtrolls_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_proto_dungeonsandtrolls_proto_rawDescGZIP(), []int{1}
}

func (x *Items) GetWeapons() []*Weapon {
	if x != nil {
		return x.Weapons
	}
	return nil
}

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PositionX int32  `protobuf:"varint,2,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY int32  `protobuf:"varint,3,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dungeonsandtrolls_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeonsandtrolls_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_proto_dungeonsandtrolls_proto_rawDescGZIP(), []int{2}
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetPositionX() int32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *Object) GetPositionY() int32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

type MapDecorations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carpets []*Object `protobuf:"bytes,1,rep,name=carpets,proto3" json:"carpets,omitempty"`
}

func (x *MapDecorations) Reset() {
	*x = MapDecorations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dungeonsandtrolls_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapDecorations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDecorations) ProtoMessage() {}

func (x *MapDecorations) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeonsandtrolls_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDecorations.ProtoReflect.Descriptor instead.
func (*MapDecorations) Descriptor() ([]byte, []int) {
	return file_proto_dungeonsandtrolls_proto_rawDescGZIP(), []int{3}
}

func (x *MapDecorations) GetCarpets() []*Object {
	if x != nil {
		return x.Carpets
	}
	return nil
}

type MapObjects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monsters []*Object `protobuf:"bytes,1,rep,name=monsters,proto3" json:"monsters,omitempty"`
	Chests   []*Object `protobuf:"bytes,2,rep,name=chests,proto3" json:"chests,omitempty"`
	Stairs   []*Object `protobuf:"bytes,3,rep,name=stairs,proto3" json:"stairs,omitempty"`
}

func (x *MapObjects) Reset() {
	*x = MapObjects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dungeonsandtrolls_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapObjects) ProtoMessage() {}

func (x *MapObjects) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeonsandtrolls_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapObjects.ProtoReflect.Descriptor instead.
func (*MapObjects) Descriptor() ([]byte, []int) {
	return file_proto_dungeonsandtrolls_proto_rawDescGZIP(), []int{4}
}

func (x *MapObjects) GetMonsters() []*Object {
	if x != nil {
		return x.Monsters
	}
	return nil
}

func (x *MapObjects) GetChests() []*Object {
	if x != nil {
		return x.Chests
	}
	return nil
}

func (x *MapObjects) GetStairs() []*Object {
	if x != nil {
		return x.Stairs
	}
	return nil
}

type Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Free    []*structpb.ListValue `protobuf:"bytes,1,rep,name=free,proto3" json:"free,omitempty"`
	Objects *MapObjects           `protobuf:"bytes,2,opt,name=objects,proto3" json:"objects,omitempty"`
}

func (x *Map) Reset() {
	*x = Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dungeonsandtrolls_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeonsandtrolls_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_proto_dungeonsandtrolls_proto_rawDescGZIP(), []int{5}
}

func (x *Map) GetFree() []*structpb.ListValue {
	if x != nil {
		return x.Free
	}
	return nil
}

func (x *Map) GetObjects() *MapObjects {
	if x != nil {
		return x.Objects
	}
	return nil
}

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map   *Map   `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Items *Items `protobuf:"bytes,2,opt,name=items,proto3" json:"items,omitempty"`
}

func (x *GameState) Reset() {
	*x = GameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dungeonsandtrolls_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dungeonsandtrolls_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_dungeonsandtrolls_proto_rawDescGZIP(), []int{6}
}

func (x *GameState) GetMap() *Map {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *GameState) GetItems() *Items {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_dungeonsandtrolls_proto protoreflect.FileDescriptor

var file_proto_dungeonsandtrolls_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73,
	0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a,
	0x06, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3c, 0x0a, 0x05, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73,
	0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x52, 0x07, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x73, 0x22, 0x5a, 0x0a, 0x06, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0x45, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x44, 0x65, 0x63, 0x6f,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x70, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65,
	0x6f, 0x6e, 0x73, 0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x63, 0x61, 0x72, 0x70, 0x65, 0x74, 0x73, 0x22, 0xa9, 0x01, 0x0a,
	0x0a, 0x4d, 0x61, 0x70, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x6d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x08, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x68, 0x65, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x61, 0x6e, 0x64,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x63,
	0x68, 0x65, 0x73, 0x74, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x69, 0x72, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73,
	0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x69, 0x72, 0x73, 0x22, 0x6e, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x12,
	0x2e, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x66, 0x72, 0x65, 0x65, 0x12,
	0x37, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x61, 0x6e, 0x64, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52,
	0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x65, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x61, 0x6e, 0x64,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12,
	0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32,
	0x53, 0x0a, 0x11, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x41, 0x6e, 0x64, 0x54, 0x72,
	0x6f, 0x6c, 0x6c, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x61,
	0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x00, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x67, 0x64, 0x67, 0x2d, 0x67, 0x61, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x64, 0x75,
	0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x73, 0x2d, 0x61, 0x6e, 0x64, 0x2d, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e,
	0x73, 0x61, 0x6e, 0x64, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_dungeonsandtrolls_proto_rawDescOnce sync.Once
	file_proto_dungeonsandtrolls_proto_rawDescData = file_proto_dungeonsandtrolls_proto_rawDesc
)

func file_proto_dungeonsandtrolls_proto_rawDescGZIP() []byte {
	file_proto_dungeonsandtrolls_proto_rawDescOnce.Do(func() {
		file_proto_dungeonsandtrolls_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dungeonsandtrolls_proto_rawDescData)
	})
	return file_proto_dungeonsandtrolls_proto_rawDescData
}

var file_proto_dungeonsandtrolls_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_dungeonsandtrolls_proto_goTypes = []interface{}{
	(*Weapon)(nil),             // 0: dungeonsandtrolls.Weapon
	(*Items)(nil),              // 1: dungeonsandtrolls.Items
	(*Object)(nil),             // 2: dungeonsandtrolls.Object
	(*MapDecorations)(nil),     // 3: dungeonsandtrolls.MapDecorations
	(*MapObjects)(nil),         // 4: dungeonsandtrolls.MapObjects
	(*Map)(nil),                // 5: dungeonsandtrolls.Map
	(*GameState)(nil),          // 6: dungeonsandtrolls.GameState
	(*structpb.ListValue)(nil), // 7: google.protobuf.ListValue
	(*emptypb.Empty)(nil),      // 8: google.protobuf.Empty
}
var file_proto_dungeonsandtrolls_proto_depIdxs = []int32{
	0,  // 0: dungeonsandtrolls.Items.weapons:type_name -> dungeonsandtrolls.Weapon
	2,  // 1: dungeonsandtrolls.MapDecorations.carpets:type_name -> dungeonsandtrolls.Object
	2,  // 2: dungeonsandtrolls.MapObjects.monsters:type_name -> dungeonsandtrolls.Object
	2,  // 3: dungeonsandtrolls.MapObjects.chests:type_name -> dungeonsandtrolls.Object
	2,  // 4: dungeonsandtrolls.MapObjects.stairs:type_name -> dungeonsandtrolls.Object
	7,  // 5: dungeonsandtrolls.Map.free:type_name -> google.protobuf.ListValue
	4,  // 6: dungeonsandtrolls.Map.objects:type_name -> dungeonsandtrolls.MapObjects
	5,  // 7: dungeonsandtrolls.GameState.map:type_name -> dungeonsandtrolls.Map
	1,  // 8: dungeonsandtrolls.GameState.items:type_name -> dungeonsandtrolls.Items
	8,  // 9: dungeonsandtrolls.DungeonsAndTrolls.Game:input_type -> google.protobuf.Empty
	6,  // 10: dungeonsandtrolls.DungeonsAndTrolls.Game:output_type -> dungeonsandtrolls.GameState
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_dungeonsandtrolls_proto_init() }
func file_proto_dungeonsandtrolls_proto_init() {
	if File_proto_dungeonsandtrolls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dungeonsandtrolls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weapon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dungeonsandtrolls_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Items); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dungeonsandtrolls_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dungeonsandtrolls_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapDecorations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dungeonsandtrolls_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapObjects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dungeonsandtrolls_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dungeonsandtrolls_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dungeonsandtrolls_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dungeonsandtrolls_proto_goTypes,
		DependencyIndexes: file_proto_dungeonsandtrolls_proto_depIdxs,
		MessageInfos:      file_proto_dungeonsandtrolls_proto_msgTypes,
	}.Build()
	File_proto_dungeonsandtrolls_proto = out.File
	file_proto_dungeonsandtrolls_proto_rawDesc = nil
	file_proto_dungeonsandtrolls_proto_goTypes = nil
	file_proto_dungeonsandtrolls_proto_depIdxs = nil
}
